#!/bin/bash

set -e

template_prefix="postfix"
STEMCELL_OS=${STEMCELL_OS:-ubuntu}

infrastructure=$1

fail() {
	echo >&2 $*
}

if [[ "$infrastructure" != "aws-ec2" && "$infrastructure" != "warden" ]] ; then
  fail "usage: ./make_manifest <aws-ec2|warden>"
  exit 1
fi

case "${infrastructure}/${STEMCELL_OS}" in
  (warden/*)       STEMCELL_URL="https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent" ;;
  (aws-ec2/ubuntu) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-ubuntu-trusty-go_agent" ;;
  (aws-ec2/centos) STEMCELL_URL="https://bosh.io/d/stemcells/bosh-aws-xen-centos-7-go_agent" ;;
  (*)
    fail "Invalid infrastructure or OS specified."
    exit 1
    ;;
esac

shift

templates=$(dirname $0)
release=$templates/..
tmpdir=$release/tmp
NAME=$template_prefix-$infrastructure
STEMCELL="bosh-warden-boshlite-ubuntu-trusty-go_agent"
DIRECTOR_UUID=`bosh -e vbox env --column=uuid | cat`

mkdir -p $tmpdir
cp $templates/stub.yml $tmpdir/stub-with-uuid.yml
echo $DIRECTOR_NAME $DIRECTOR_CPI $DIRECTOR_UUID $STEMCELL
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" $tmpdir/stub-with-uuid.yml
perl -pi -e "s/NAME/$NAME/g" $tmpdir/stub-with-uuid.yml
perl -pi -e "s/STEMCELL/$STEMCELL/g" $tmpdir/stub-with-uuid.yml

if ! [ -x "$(command -v spruce)" ]; then
  echo 'spruce is not installed. Please download at https://github.com/geofffranks/spruce/releases' >&2
fi

spruce merge --prune meta \
  $templates/deployment.yml \
  $templates/jobs.yml \
  $templates/infrastructure-${infrastructure}.yml \
  $tmpdir/stub-with-uuid.yml \
  $* > $tmpdir/$NAME-manifest.yml

#bosh deployment $tmpdir/$NAME-manifest.yml
#bosh status
